on:
  push:
    branches:
      - main

env:
  APP_NAME: ${APP_NAME}

jobs:
  build:
    name: Build for all platforms
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Extra steps for macOS
        if: matrix.os == 'macos-latest'
        run: |
          npm i -g nan
          export NODE_PATH=$(npm root -g)
          npm i -D macos-alias
      - name: Install dependencies
        run: |
          npm i
      - name: Build
        run: npm run build
      - name: Upload artifact for next job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: out/make/

  release:
    name: Package and Release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create tag
        id: create_tag
        uses: Klemensas/action-autotag@stable
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_prefix: "v"
          tag_suffix: "-alpha"
      - name: Download artifact from previous job
        uses: actions/download-artifact@v2
        with:
          name: build
      - run: ls -lah
      - name: Move build assets
        run: |
          mkdir releases
          mv ./zip/linux/x64/*.zip releases/${APP_NAME}_linux.zip
          mv ./deb/x64/*.deb releases/${APP_NAME}_debian.deb
          mv ./rpm/x64/*.rpm releases/${APP_NAME}_rpm.rpm
          mv ./zip/darwin/x64/*.zip releases/${APP_NAME}_macOS.zip
          mv ./*.dmg releases/${APP_NAME}_macOS.dmg
          mv ./squirrel.windows/x64/*.exe releases/${APP_NAME}_windows.exe
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tagname }}
          release_name: ${{ env.APP_NAME }} ${{ steps.create_tag.outputs.tagname }}
          draft: false
          prerelease: false
      - name: Upload linux package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/${{ env.APP_NAME }}_linux.zip
          asset_name: ${{ env.APP_NAME }}_linux.zip
          asset_content_type: application/zip
      - name: Upload debian package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/${{ env.APP_NAME }}_debian.zip
          asset_name: ${{ env.APP_NAME }}_debian.zip
          asset_content_type: application/zip
      - name: Upload rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/${{ env.APP_NAME }}_rpm.rpm
          asset_name: ${{ env.APP_NAME }}_rpm.rpm
          asset_content_type: application/zip
      - name: Upload macOS package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/${{ env.APP_NAME }}_macOS.zip
          asset_name: ${{ env.APP_NAME }}_macOS.zip
          asset_content_type: application/zip
      - name: Upload macOS DMG package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/${{ env.APP_NAME }}_macOS.dmg
          asset_name: ${{ env.APP_NAME }}_macOS.dmg
          asset_content_type: application/zip
      - name: Upload windows package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/${{ env.APP_NAME }}_windows.exe
          asset_name: ${{ env.APP_NAME }}_windows.exe
          asset_content_type: application/zip
