on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Lint and check for issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint