on:
  push:
    branches:
      - master

jobs:
  test:
    name: Lint and check for errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint