on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test and Check for errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: npm test